### ISSUE TITLE
benchmark reading is included?

### ISSUE THREAD

**Issue by 18601673727** [sassman/ssd-benchmark-rs#11]

**Comment by sassman** [comment]
The data is generated in memory, but only the writing is measured. 

So the timings does not contaminants reading times.

Does this answer your question?

**Comment by 18601673727** [comment]
Well, think it's too complicated for me, as my poor understanding:
```
Total bytes written / Total time elapsed = Average Writting Speed
Total bytes read / Total time elapsed = Average Reading Speed
```
For each kind of speed, do 4K 64K 1M 32M 256M 1G 4G runnings then tabulate results out meet my expectation, nice tool though, super simple parameter design!

Thanks!
