### ISSUE TITLE
Container image build

### ISSUE THREAD

**Issue by damdo** [sassman/ssd-benchmark-rs#12]
Hey @sassman, thank you for this project.
I'm currently using it from within a container to benchmark disk speed on Kubernetes clusters and for this reason I'm building myself a container image of this project.

I think would be good to have an "official" container image build coming directly from here. Maybe something that can be added to the already existing GitHub Actions set up for the project, which could build and push an image to a container registry as soon as there is a new release.

Thank you.

**Comment by sassman** [comment]
Hey @damdo, 
That sounds like a good idea to me.
